ublk: use count in ublk_io_xmit() in release builds
count was unused in release builds. Otherwise following
error is produced on clang build:

19:30:56  ublk.c:974:14: error: variable 'count' set but not used
[-Werror,-Wunused-but-set-variable]
19:30:56          int rc = 0, count = 0, tag;
19:30:56                      ^
19:30:56  1 error generated.

Signed-off-by: Tomasz Zawadzki <tomasz.zawadzki@intel.com>
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/16450 (master)

(cherry picked from commit 2f8a723edf09a645c2399735c5bfb3239b932ec7)
Change-Id: If7ca88de37ed6e40826e09b055355c07f67c8869
Signed-off-by: Krzysztof Karas <krzysztof.karas@intel.com>
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/16490
Reviewed-by: Jim Harris <james.r.harris@intel.com>
Reviewed-by: Tomasz Zawadzki <tomasz.zawadzki@intel.com>
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>