lib/ftl: Fix "unused function" error under clang
This is targeted to fix the following error seen under clang:

  ftl_nv_cache.c:54:1: error: unused function 'nvc_data_blocks'
     [-Werror,-Wunused-function]
  nvc_data_blocks(struct ftl_nv_cache *nv_cache)
  ^

Signed-off-by: Michal Berger <michal.berger@intel.com>
Change-Id: I11d52e76df5872819770d9468b6fa4ae54d8927c
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/14055
Community-CI: Mellanox Build Bot
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
Reviewed-by: <sebastian.brzezinka@intel.com>
Reviewed-by: Aleksey Marchuk <alexeymar@nvidia.com>
Reviewed-by: Tomasz Zawadzki <tomasz.zawadzki@intel.com>
Reviewed-by: Dong Yi <dongx.yi@intel.com>