app/lspci: Link libmlx5 when mlx5_dv RDMA provider is used
It is necessary to link libmlx5, otherwise we'll get a linkage error:
libspdk_rdma.a(rdma_mlx5_dv.o): In function `spdk_rdma_qp_create':
rdma_mlx5_dv.c:123: undefined reference to `mlx5dv_create_qp'

Signed-off-by: Alexey Marchuk <alexeymar@mellanox.com>
Change-Id: Ib3ee4fd0a6e0c9d605a558da0be47c99af4bc366
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/4457
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
Reviewed-by: Jim Harris <james.r.harris@intel.com>
Reviewed-by: Shuhei Matsumoto <shuhei.matsumoto.xt@hitachi.com>
Reviewed-by: Ben Walker <benjamin.walker@intel.com>